/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paneles;
import Clases.*;
import java.awt.Color;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Arian
 */
public final class panel_MenuPrincipalE extends javax.swing.JFrame {

    /**
     * Creates new form panel_MenuPrincipal
     */
    static Conexion CX = new Conexion();
    public panel_MenuPrincipalE() {
        initComponents();

        this.setLocationRelativeTo(null); // Ventana en el centro de la pantalla

        MostrarTabla();

    }
    
    public void MostrarTabla(){
        DefaultTableModel modelo = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row,int column){
                    
                    return false;   
                }
        };
        try {
            
            
            
            modelo.addColumn("ID");
            modelo.addColumn("Usuario");
            modelo.addColumn("N.C.Corrientes");
            modelo.addColumn("N.C.Credito");
            TB_tablaClientes.setModel(modelo);
            
            String SQL = "SELECT * FROM clientes";
            Statement st = CX.Conector().createStatement();
            ResultSet rs = st.executeQuery(SQL);
            String[] Datos = new String[4];
            while(rs.next()){
                Datos[0] = rs.getString(1);
                Datos[1] = rs.getString(2);
                Datos[2] = rs.getString(4);
                Datos[3] = rs.getString(5);
                modelo.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_MenuPrincipalE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void AccesoEmpleado(String ID){
        try {
            String query = "SELECT * FROM usuarios WHERE id ="+ID+"";
            Statement st = CX.Conector().createStatement();
            ResultSet rs = st.executeQuery(query);
            if (rs.next()){
                String Nombre = rs.getString(2);
                LB_NombreE.setText("Empleado: "+Nombre);
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_MenuPrincipalE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LB_NombreE = new javax.swing.JLabel();
        BT_clienteNuevo = new javax.swing.JButton();
        BT_CerrarSesion = new javax.swing.JButton();
        BT_EditarPerfil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TB_tablaClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        TXT_Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BT_crearCuenta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sesion Empleado");
        setBackground(new java.awt.Color(153, 255, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setText("Banco Venedit ");

        LB_NombreE.setFont(new java.awt.Font("Nirmala UI", 3, 18)); // NOI18N
        LB_NombreE.setText("Empleado: ");

        BT_clienteNuevo.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        BT_clienteNuevo.setText("Cliente Nuevo");
        BT_clienteNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BT_clienteNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_clienteNuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BT_clienteNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BT_clienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_clienteNuevoActionPerformed(evt);
            }
        });

        BT_CerrarSesion.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        BT_CerrarSesion.setText("Cerrar Sesion");
        BT_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CerrarSesionActionPerformed(evt);
            }
        });

        BT_EditarPerfil.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        BT_EditarPerfil.setText("Editar Perfil");
        BT_EditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EditarPerfilActionPerformed(evt);
            }
        });

        TB_tablaClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TB_tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TB_tablaClientes.setToolTipText("");
        TB_tablaClientes.setEditingColumn(1);
        TB_tablaClientes.setEditingRow(1);
        TB_tablaClientes.setGridColor(new java.awt.Color(153, 153, 153));
        TB_tablaClientes.setRowHeight(25);
        TB_tablaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TB_tablaClientes.setShowGrid(true);
        TB_tablaClientes.getTableHeader().setReorderingAllowed(false);
        TB_tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TB_tablaClientes);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TXT_Usuario.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        TXT_Usuario.setForeground(new java.awt.Color(0, 153, 153));
        TXT_Usuario.setText("Cliente");
        TXT_Usuario.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        TXT_Usuario.setEnabled(false);
        TXT_Usuario.setSelectedTextColor(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel3.setText("Usuario :");

        jButton1.setBackground(new java.awt.Color(0, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BT_crearCuenta.setBackground(new java.awt.Color(0, 255, 102));
        BT_crearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BT_crearCuenta.setText("Crear");
        BT_crearCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BT_crearCuenta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BT_crearCuenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BT_crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_crearCuentaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BT_crearCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_crearCuenta, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Lista de Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(688, 688, 688)
                        .addComponent(BT_clienteNuevo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LB_NombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BT_EditarPerfil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT_CerrarSesion)))
                        .addGap(2, 2, 2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT_CerrarSesion)
                            .addComponent(BT_EditarPerfil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LB_NombreE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(BT_clienteNuevo)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_clienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_clienteNuevoActionPerformed
        // TODO add your handling code here:
        panel_RegistrarCliente Registrador = new panel_RegistrarCliente();
        Registrador.setVisible(true);
        Registrador.RecibirMenu(this);
        BT_CerrarSesion.setEnabled(false);
        BT_EditarPerfil.setEnabled(false);
        BT_clienteNuevo.setEnabled(false);
        if(evt.getSource()==BT_clienteNuevo){
            this.setVisible(false);
        }
    }//GEN-LAST:event_BT_clienteNuevoActionPerformed
    public void ActivarBotones(){
        BT_CerrarSesion.setEnabled(true);
        BT_EditarPerfil.setEnabled(true);
        BT_clienteNuevo.setEnabled(true);
    }
    
    private void BT_EditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EditarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_EditarPerfilActionPerformed


    private void BT_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CerrarSesionActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==BT_CerrarSesion){// Evalua si se presiono el boton
            this.setVisible(false);
            new panel_InicioSesion().setVisible(true);
        }
    }//GEN-LAST:event_BT_CerrarSesionActionPerformed

    private void BT_crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_crearCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_crearCuentaActionPerformed

    private void TB_tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_tablaClientesMouseClicked
        // TODO add your handling code here:
        int selec = TB_tablaClientes.rowAtPoint(evt.getPoint());
        TXT_Usuario.setText(String.valueOf(TB_tablaClientes.getValueAt(selec,1)));
    }//GEN-LAST:event_TB_tablaClientesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_MenuPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_MenuPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_MenuPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_MenuPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_MenuPrincipalE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CerrarSesion;
    private javax.swing.JButton BT_EditarPerfil;
    private javax.swing.JButton BT_clienteNuevo;
    private javax.swing.JButton BT_crearCuenta;
    private javax.swing.JLabel LB_NombreE;
    private javax.swing.JTable TB_tablaClientes;
    private javax.swing.JTextField TXT_Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
