/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paneles;
import java.sql.*;
import Clases.*;
import javax.swing.table.DefaultTableModel;

import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Arian
 */
public class panel_OperarClienteE extends javax.swing.JFrame {
    static Connection CN;
    static Clientes Cliente;
    /**
     * Creates new form panel_OperarCliente
     */
    public panel_OperarClienteE() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void recibirConec(Connection CN){
        this.CN = CN;
    }
    public void recibirCliente(Clientes client){
        this.Cliente = client;
        ActualizarTabla();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Cuentas = new javax.swing.JTable();
        LB_UsuarioCliente = new javax.swing.JLabel();
        LB_Cliente1 = new javax.swing.JLabel();
        LB_Cliente2 = new javax.swing.JLabel();
        LB_NombreCliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        TB_Cuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TB_Cuentas);

        LB_UsuarioCliente.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        LB_UsuarioCliente.setText("nameuser");

        LB_Cliente1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        LB_Cliente1.setForeground(new java.awt.Color(0, 0, 153));
        LB_Cliente1.setText("Nombre :");

        LB_Cliente2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        LB_Cliente2.setForeground(new java.awt.Color(0, 0, 153));
        LB_Cliente2.setText("Cliente: ");

        LB_NombreCliente.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        LB_NombreCliente.setText("Nombre Completo");

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(LB_Cliente2)
                .addGap(29, 29, 29)
                .addComponent(LB_UsuarioCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(LB_Cliente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LB_NombreCliente)
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_UsuarioCliente)
                    .addComponent(LB_Cliente1)
                    .addComponent(LB_Cliente2)
                    .addComponent(LB_NombreCliente))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton1){
            this.setVisible(false);
            new panel_MenuPrincipalEmpleado().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void ActualizarTabla(){
        DefaultTableModel modelo = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;   
                }  
        };
        try {
            modelo.addColumn("N° Cuenta");
            modelo.addColumn("Monto");
            TB_Cuentas.setModel(modelo);
            //
            //  Cuentas Corriente
            //
            String[] txCuentasCorriente = new String[2];
            txCuentasCorriente[0] = "Cuentas";
            txCuentasCorriente[1] = "Corriente";
            modelo.addRow(txCuentasCorriente);
            String SQL = "SELECT * FROM cuentasCorrientes WHERE conexCliente = "+Cliente.getIdCliente()+" ";
            Statement st = CN.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            String[] Datos = new String[2];
            while(rs.next()){
                Datos[0] = rs.getString(2);
                Datos[1] = rs.getString(3);
                modelo.addRow(Datos);
            }
            /*
                Cuentas Credito
            */
            txCuentasCorriente = new String[2];
            txCuentasCorriente[0] = "Cuentas";
            txCuentasCorriente[1] = "Credito";
            modelo.addRow(txCuentasCorriente);
            txCuentasCorriente[0] = "N° Cuenta";
            txCuentasCorriente[1] = "Credito";
            modelo.addRow(txCuentasCorriente);
            SQL = "SELECT * FROM cuentasCredito WHERE conexCliente = "+Cliente.getIdCliente()+" ";
            st = CN.createStatement();
            rs = st.executeQuery(SQL);
            while(rs.next()){
                Datos[0] = rs.getString(2);
                Datos[1] = rs.getString(3);
                modelo.addRow(Datos);
            }
            /*
                Cuentas Ahorro
            */
            txCuentasCorriente = new String[2];
            txCuentasCorriente[0] = "Cuentas";
            txCuentasCorriente[1] = "Ahorro";
            modelo.addRow(txCuentasCorriente);
            txCuentasCorriente[0] = "N° Cuenta";
            txCuentasCorriente[1] = "Deposito";
            modelo.addRow(txCuentasCorriente);
            SQL = "SELECT * FROM cuentasAhorro WHERE conexCliente = "+Cliente.getIdCliente()+" ";
            st = CN.createStatement();
            rs = st.executeQuery(SQL);
            while(rs.next()){
                Datos[0] = rs.getString(2);
                Datos[1] = rs.getString(3);
                modelo.addRow(Datos);
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel_MenuPrincipalEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_OperarClienteE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_OperarClienteE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_OperarClienteE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_OperarClienteE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_OperarClienteE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Cliente1;
    private javax.swing.JLabel LB_Cliente2;
    private javax.swing.JLabel LB_NombreCliente;
    private javax.swing.JLabel LB_UsuarioCliente;
    private javax.swing.JTable TB_Cuentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
